### ISSUE TITLE
TypeError ERR_INVALID_ARG_TYPE within shutdown fn

### ISSUE THREAD

**Issue by bricss** [dcolens/connect-ready#4]
An error encountered in [L:81](https://github.com/dcolens/connect-ready/blob/master/index.js#L81) that throws an **uncaughtException** if the `error` param is not passed within `shutdown()` call.

```javascript
ready.shutdown(
  'SIGTERM',
  undefined, // <- here
  graceFullShutdown,
  config.get('terminationFile'),
  logger,
);
```

Causes following error:
```shell
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received function shutdown
 at Object.writeFile (fs.js:1385:5)
 at Object.shutdown (/home/node/app/node_modules/connect-ready/index.js:95:6)
 ...
```

**Comment by dcolens** [comment]
fixed via https://github.com/dcolens/connect-ready/pull/6
